name: 'SWM: Deploy to Azure'

on:
  push:
    branches:
    - master

 
jobs:
  build_test:
    name: 'Build and Test'  
    runs-on: ubuntu-latest

    steps:
    - name: Set Environment variables
      shell: bash
      run: |
        echo "FUNCTION_APP_PATH=${{ github.workspace }}"/api >> $GITHUB_ENV
    
    - name: Check environment Variables
      shell: bash
      run: |
        echo $FUNCTION_APP_PATH
    
    - name: Checkout the repo
      uses: actions/checkout@v2
    
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.x'
    
    - name: Restore NuGet packages
      shell: bash
      run: |
        dontnet restore.
      
    - name: Build Function App
      shell: bash
      run: |
        dotnet build .
    
    - name: Test Function App
      shell: bash
      run: |
        dotnet test . -C Release

    - name: Create Function App artifact
      shell: bash
      run: |
        pushd "${{ env.FUNCTION_APP_PATH}}"
        dotnet publish . -c Release -o published
        popd

    - name: Upload Function App artifact
      uses: actions/upload-artifact@v2
      with:
        name: apiapp
        path: ${{ env.FUNCTION_APP_PATH }}/published